### ISSUE TITLE
Cortex mapper compatibility problem

### ISSUE THREAD

**Issue by paulo17** [ikkez/F3-Sugar#43]
Hi,

I think I have a problem when using Cortex with FatFree v3.4

When I instanciate the Cortex Mapper I got this error on the browser

```
Fatal error: Declaration of DB\Cortex::get() must be compatible with & Magic::get($key)
```

Could anyone help me with this ?

Thanks

**Comment by ikkez** [comment]
hi paul.
please see the dev branch of cortex, at https://github.com/ikkez/F3-Sugar/tree/dev-cortex/Cortex
it is already compatible with F3 v3.4. I wanted to release Cortex v1.3 along with the F3 release, but there were some issues in the 3.4 release, so i hold it back so far. If you get any trouble, see the F3 3.4.1-dev branch. 
I'll push the new Cortex version to the master soon.

**Comment by paulo17** [comment]
It works, thank you a lot. 
Good luck for the development of Cortex 1.3. I hope you will be able to release it soon.

**Comment by ikkez** [comment]
Alright, tested once more with the release. And it's working fine so far (at least all unit tests passed) :smile: 
So here it is: https://github.com/ikkez/F3-Sugar/releases/tag/cortex-1.3.0
