### ISSUE TITLE
field type in fluid mode

### ISSUE THREAD

**Issue by xmory** [ikkez/F3-Sugar#45]
When I tried model in fluid mode, I found that Cortex tried to create table according to value. How about checking $fieldConf first. If the field type has been given,  create them, if not, then try to guess the type?
Thanks to your nice work.

**Comment by ikkez** [comment]
hi. Well this is what the setup() method does. It creates table and columns based on the $fieldConf array. If you have a model and already defined some fields, why not just run Model::setup() then?

**Comment by xmory** [comment]
My work flow is,   writing model first, adding some fields needed.  With the help of the fluid mode, I don't need to define all fields at the beginning. With the growth of the project,  I can add new fields, or reset a field type. 
It seems that whenever I change the $fieldConf, I need to run Model::setup() first?

**Comment by ikkez** [comment]
>  It seems that whenever I change the $fieldConf, I need to run Model::setup() first? 

Basically yes. If you have fluid mode turned on, you don't need any fieldConf at all, except for adding relations if needed. It would not be that hard to add a fieldConf check here, i can do that. But in the end i guess you need an install routine nevertheless, where you call the setup method to initialize the final db tables. What i think could be useful is a generator for the $fieldConf array based on the existing table. So you can fluidly prototype the model, and paste the final fieldConf later into it. 
Do you think that the fluid mode should try to alter or update column types if their fieldConf differs from the existing table scheme?

**Comment by xmory** [comment]
I don't think detecteing every filed while running is needed, but when we get a missed field, it may be better :) 
I want to create a model config file to define model fieldConf. In this file, I will include not only normal field type etc, but also validate rules for fields. When a model object is created or updated, validator will take affects. When the form view of the model is rendering, the file will also be used to create client validate codes. 
I think it will be useful. I don't need to repeat code once more.
In this case, fieldConf is needed :)  
Sorry for my poor English. Thanks to your answer.

**Comment by ikkez** [comment]
solution committed. Is that what you was thinking of?

**Comment by adaniello** [comment]
@ikkez, i understand that @xmory wants add "also validate rules for fields" in config, what do you think about?

**Comment by xmory** [comment]
yes，it's what i want. ^_^
thanks.

**Comment by ikkez** [comment]
yeah that is absolutely reasonable to put some validation setup into the fieldConf array as well. This is a good idea and me and others are already doing so. It's up to you how you want to implement this. You can use a custom setter event, or a save or update hook. use a 3rd party validation library or just add some simple logic on your own. 

As example. In one project i used this:

```php
class BaseModel extends \DB\Cortex {

	// persistence settings
	protected $table, $db, $fieldConf;

	public function __construct() {
		$this->db = 'DB';
		parent::__construct();
		// validation & error handler
		$class = get_called_class(); // PHP 5.3 bug
		$saveHandler = function($self) use($class) {
			/** @var \Base $f3 */
			$f3 = \Base::instance();
			foreach($self->getFieldConfiguration() as $field=>$conf) {
				if (isset($conf['type'])) {
					$val = $self->get($field);
					$model = strtolower(str_replace('\\','.',$class));
					// check required fields
					if (isset($conf['required'])	&& (empty($val) && $val!==0)) {
						if (!$f3->exists('error.'.$model.'.'.$field.'.required',$errText))
							$errText = $field.' field is required';
						$f3->error(400, $errText);
					}
					// check unique
					if (isset($conf['unique'])) {
						$filter = $self->dry()
							// new record
							? array($field.' = ?',$val)
							// change field of existing record, excludes itself
							: array($field.' = ? and _id != ?',$val,$self->_id);
						if ($self->findone($filter)) {
							if (!$f3->exists('error.'.$model.'.'.$field.'.taken',$errText))
								$errText = 'this '.$field.' is already taken';
							$f3->error(400, $errText);
						}
					}
				}
			}
		};
		$this->beforesave($saveHandler);
	}
}
```
error messages are defined in language files, like `error.user.email.unique = There is already an account using that email` or `error.comment.text.required = Please enter your message`

I'll add that as a demo to fabulog soon.

**Comment by adaniello** [comment]
@ikkez simply perfect! Why not add in config general definitions to validate as required, unique and regex role?

**Comment by ikkez** [comment]
Well i think that integration of validation should be made with hooks (see [supported events](https://github.com/ikkez/F3-Sugar/tree/master-v3/Cortex#event-handlers)), as the way how to define rules could become very different according to the validation class you use or not use (see [Respect/Validation](https://github.com/Respect/Validation) or [GUMP](https://github.com/Wixel/GUMP)). I.e. if using GUMP, you probably what to use 'validate'=>'required|max_len,100|min_len,6'. But implementing other validators probably works differently. Basically you can put whatever you like into the $fieldConf array to fit your needs. Even may unique example isn't that generic as it might seems at first sight. maybe someone need to add some other fields in the filter here. So i can add examples how to add basic or dynamic validation, but i don't see full bloated integration of this yet. If you have any questions or ideas regarding that, please file a new issue ;) i guess this here is solved now with the made commit. cheers :beers:

**Comment by adaniello** [comment]
thanks
