### ISSUE TITLE
Possible bug on count relation

### ISSUE THREAD

**Issue by slifin** [ikkez/F3-Sugar#46]
"PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JOIN (SELECT `id`,`recipe_id` FROM `foods` GROUP BY `recipe_id`) AS `sub` ON `fo' at line 1"

I get the error with this query:

    $foods->countRel('recipe_id');
    $rs=$foods->find([
			'image REGEXP ?',implode('|', $searchIds)
			]);

Food

    <?php
    namespace models;
    class Foods extends \models\Base{
        protected $db = 'DB',
        $table = 'foods',
        $fluid = true,
        $fieldConf = [
        'recipe_id'=> [
        'belongs-to-one'=>['\models\recipes','id'],
        'type' => \DB\SQL\Schema::DT_INT4
        ]
        ];
    }

Recipes

    <?php
    namespace models;
    class Recipes extends \models\Base{
        protected $db = 'DB',
        $table = 'recipes',
        $fluid = true,
        $fieldConf = [
        'id'=>['type'=>\DB\SQL\Schema::DT_INT4],
        'food_id'=> ['has-many'=>['\models\foods','recipe_id']]
        ];
    }

**Comment by ikkez** [comment]
Hi.  This error is probably related to this framework issue: https://github.com/bcosca/fatfree/issues/757
The grouping bug itself is already patched in the F3 nightly core. try to grab a copy of https://github.com/bcosca/fatfree-core and try again. 
Beside of that, I am not sure if your REGEX filter does work like this. Maybe we need to make some little adjustments to make it work, but just give it a try first.

**Comment by ikkez** [comment]
hey @slifin, any news on this? Does updating the F3 libs, fix your issue?

**Comment by slifin** [comment]
I moved over to using match against in a raw SQL query so I no longer have the test case for this :(

**Comment by ikkez** [comment]
no problem. i think it was the grouping bug in the F3 3.4 release, which caused this - i had the same issue. So I'll close this here. thanks anyway
