### ISSUE TITLE
Collection does not exists

### ISSUE THREAD

**Issue by mneimne** [ikkez/F3-Sugar#47]
some times  am getting this error "This Collection does not exist: cortex_collection_55118e03d7c29".
![capture](https://cloud.githubusercontent.com/assets/1798784/6806764/724ef66e-d253-11e4-976b-50abda839d08.PNG)

i was not able reproduce the error with a scenario.

**Comment by ikkez** [comment]
Hi. 
Well this could only happen when a mapper, that "lives" in a collection, failed to find that collection to get or set some relational mappers that also live there. A case to reproduce this is:

```php
$results = $news->find();
$news1 = $result[0];
unset($result);
var_dump($news1->author->name);
```
The when the php garbage collector kicks in, `$result->__destruct();` is called, which drops the collection in the Registry. Hence the news1 model can't find it anymore when it tries to ask the `$results` collection for some authors. Do you have some caching going on or use any single model from a result independently somewhere?
I cloud add a check when the collection was not found, so it I'll skips that part and continiues. Depending on your app program flow, this could maybe add some additional db queries. Or we keep all collections in the Registry, and not delete them, but this could eat up more memory. Maybe some references to the Registry could also do the trick. I'll investigate this.

**Comment by ikkez** [comment]
this should do the trick.
