### ISSUE TITLE
empty attribute by FooForms

### ISSUE THREAD

**Issue by stvowi** [ikkez/F3-Sugar#50]
wenn man beim input tag leere Attribute verwendet, wird das Formular nicht komplett gerendert. Das führt zu unnötiger Fehlersuche.

Beispiel : input type="text" name="input1" placeholder=""

**Comment by ikkez** [comment]
Kann ich leider nicht reproduzieren. Hier geht es. Habe es mir der F3 v3.5.1-dev getestet.

**Comment by Rayne** [comment]
Could be related to this fixed bug: https://github.com/bcosca/fatfree/issues/854

**Comment by ikkez** [comment]
yeah that's it.
