### ISSUE TITLE
Decoding problem in parseCSV(); function

### ISSUE THREAD

**Issue by exodus4d** [ikkez/F3-Sugar#52]
Hello :)

I have problem by using the `$scheet->parseCSV();` function. I have a function that exports table data from a `Cortex\Model` by using the `$scheet->renderCSV();` function:

``` php
public function exportData(){
    $tableModifier = static::getTableModifier()
    $headers = $tableModifier->getCols();

    // just get the records with existing columns
    // -> no "virtual" fields or "new" columns
    $this->fields($headers);
    $allRecords = $this->find();
    $tableData = $allRecords->castAll();

    // format data -> "id" must be first key
    foreach($tableData as &$rowData){
        $rowData = [$this->primary => $rowData['_id']] + $rowData;
        unset($rowData['_id']);
    }

    $sheet = \Sheet::instance();
    $sheet->renderCSV($tableData, $headers, $this->getTable() . '.csv');
}
```

Now i have a `importData()` function where I would like to to parse this *.cvg file and do some DB importing stuff later on.
##### Problem
- The *.cvg file is encoded as **UTF-16LE**  by default [L210](https://github.com/ikkez/F3-Sugar/blob/master-v3/Sheet/sheet.php#L210). The `parseCSV()` function does not check the encoding of the file. Therefor this RegEx fails [L33](https://github.com/ikkez/F3-Sugar/blob/master-v3/Sheet/sheet.php#L33), because of the prefix: `\xFF\xFE`. Here is my [export.csv](https://gist.github.com/exodus4d/a652b8eac42181f48668)
- Maybe this is something OS specific and will not occur on other systems. (I have WIN)
##### Suggestion
1. We could check (and remove) the encoding prefix after `file_get_contents()`. Something link this (http://sapeg.in/2013/12/527/). I don´t know if there is something available from PHP itselfe.
2. We could add optional parameters for en/deconding to the functions.

**Comment by exodus4d** [comment]
I found a solution:
I have to add **UTF-16LE** as internal_encoding before reading the file.
```
iconv_set_encoding("internal_encoding", "UTF-16LE");
var_dump(iconv_get_encoding('all');
```

**Comment by ikkez** [comment]
well,... I added this because some older MS Excel version have problems otherwise. So, maybe the RegEx should be patched to recognize the utf16 bom?! funny,.. I have not tried yet to reimport csv files which where generated from itself. As an alternative, you can also use the `dumpCSV` method instead, safe the file on the disk and provide a download link. but maybe the regex fix would be better.

**Comment by exodus4d** [comment]
From my side, we could close this issue.

**Comment by ikkez** [comment]
Tested. I had no issues.
