### ISSUE TITLE
Stop routing

### ISSUE THREAD

**Issue by Phisherman** [ikkez/F3-Sugar#53]
I want to implement an JWT authentication with the middleware module. Therefore I need to stop the route parsing if the authentication fails. How would you implement something like that?

I thought about this:
```php
$apiRouteControllerPrefix = 'schulungsverwaltung\controllers\api';
\Middleware::instance()->before("GET /api/events/*", function (\Base $f3) use ($apiRouteControllerPrefix) {
    if (true) {
        echo "TODO: Implement Auth";
    } else {
        $f3->route('GET /api/events', $apiRouteControllerPrefix . '\EventController->getEvents');
        $f3->route('GET /api/events/@id', $apiRouteControllerPrefix . '\EventController->getSpecificEvent');
    }
});
```

The problem is that the "normal" router will complain about not allowed methods.
![image](https://cloud.githubusercontent.com/assets/2873986/14342400/bbd16378-fc99-11e5-8a16-6c93a49f3200.png)

**Comment by ikkez** [comment]
You could just return `false` in your handler and fetch that at the run call:

```php
\Middleware::instance()->before("GET /foo/*", function (\Base $f3) {
    if (true) {
        echo "TODO: Implement Auth";
    } else {
        return false;
    }
});

if (\Middleware::instance()->run()) {
  $f3->run();
} else {
  echo "middleware preflight failed";
}
```

**Comment by Phisherman** [comment]
Nice idea. Thanks!
