### ISSUE TITLE
[Pagination] Field for counting displayed items

### ISSUE THREAD

**Issue by kumy** [ikkez/F3-Sugar#58]
For a project I'm working on, I need to have the pagination the pagination to include the number of displayed items. At the moment, there is no possibility to get the necessary information in the template variables.

PR coming.

ex:
```
Showing items 1 - 5 (of 23)
```

**Comment by ikkez** [comment]
Hi kumy. Sorry for the delay. All those xmas and new years holidays and things to do, you know ;)

Well your requirement is already possible. The F3 Mapper->paginate returns all data you need to calculate and display the item count. I.e.:

```php
$page = \Pagination::findCurrentPage();
$limit = 10;
$out = $job->paginate($page-1, $limit);
$f3->set('results', $out);
```
html:
```html
<p>Total results: <b>{{ @results.total }}</b></p>
<p>Showing items: <b>{{ @results.limit * @results.pos + 1 }} - {{ @results.limit * @results.pos + count(@results.subset) }}</b></p>
<hr>
<div class="search_result_top clearfix">
  <F3:pagebrowser items="{{@results.total}}" limit="{{@results.limit}}" src="templates/pagebrowser.html" token-prefix="page-" />
</div>
```

If you don't want to separate this, you can of course put that all into a custom `pagebrowser.html` template file.
