### ISSUE TITLE
How to include query string in pages

### ISSUE THREAD

**Issue by mneimne** [ikkez/F3-Sugar#62]
i have a listing page with a search engine, how can I include the query string in the next pages ?

**Comment by ikkez** [comment]
You can alter the template and just put the query string there

```html
<a href="{{@BASE, @pg.route, @pg.prefix.@pg.nextPage}}?{{@QUERY}}">
```

**Comment by mneimne** [comment]
Thanks for the tip, maybe we can include it in the original code example ?
